language: php
php:
- 7.2
- 7.3
cache:
  directories:
  - vendor
notifications:
  email: false
script: echo 'Orgmanager Running'
deploy:
  provider: heroku
  api_key:
    secure: YndxedtYAZOzrH5BDSf0s83QyYaOWWrqnYQsUOzRIoGPaMKLfCXe7/5XG8Iv5eLXfewmhe82l36phjq3qsyoHbKxhVCUGkeggeYJooLXyAR8DOArgcLZ2rFLE5d5F6rfvLVfWRzELpw2vdFbeqFUFYZElnZlO1i42FNKLDiWp1lgJ1p8FX6XJSRWY5w3j8lX14rOdB5Dg3W4B6RJLko3FTEag1njEl2Q2Fee3RagrDtyNatyMF/EXr6A2gP3XIHt3i+GGyfBX+eSmcRg+8SQZYvNR+QjUbV8YWWm1ycUd98pfQU/Po1Kzuuc6NF6aytwbZ2pf1trptk3xyZhqU5SyXbAS91thk5jFU3PrVy3i3pwIzjBFs9ab9r5qKdlhysQ7FXEOY0yVBAdFhNGOOgq2XS9qPjbiVwUZ4UJ+80pzbZGhhysMcLcpaaVyy/f60IMYTVBQvE0loFxMMHVkkjA5ILNM6S1zdBpy/nELDHRJxWlUay9oZldLSe/ViKHsiy5pTFfslvyub+px4/Jm5KsqpM/zp1/wPWWSrDYD/fWQ3k/t37ehEDh2k4nnUMT2V1ZmvQZwjoGY0d/9K+3RFI+K8v3yOzw7xlfSgPUnJuLycy42NF/chkz1NFlrkfIIFdiPM5hL/BuHfjsaea18H4gpK8YwKZrWKi475Fop7Xospg=
  app: orgmanger
  repo: kumuditha-udayanga/orgmanager
